name: sky_map
description: "Night sky map app with real-time sensor updates."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  geolocator: ^12.0.0
  sensors_plus: ^6.1.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  
  uses-material-design: true

  
